created generic button component with its styles
Ran-Regev-HLS/Pokedex pull request #2
Opened 2024-11-10 14:37 UTC by Ran-Regev-HLS

2024-11-11 11:49 UTC, kfir-azu requested changes

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +  children?: React.ReactNode;
import ReactNode from react

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +  variant:
Create an enum 
```
export enum ButtonVariant {
PRIMARY="primary",
etc...
}
```

checkout raycast change case extension - you can do realy cool stuff when defining enums (Remind me tomorrow to show you how i would do that)

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +  size: "large" | "medium" | "small";
Same here - create an enum - ButtonSize

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +export interface ButtonProps {
What about start and end icon?

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +  children?: React.ReactNode;
Do i have to send a react node to the button as children?
If i only want to show some text why would i have to wrap it in a reactNode?

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +    width: Hug (80px) px;
You are not supposed to use the Hug and Fixed properties from the figma - this is for the disgeners. I also asked it when I started working with figma

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +    padding: 12px 16px 12px 16px;
Create a spacing object in the same file you defined the colors object.
export const spacing = {
1: '4px',
2: '8px',
go on until 40px
}

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +    border-radius: 4px 0px 0px 0px;
Same comment as comment about spacing.
create border radius constant and use it

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +    gap: 4px;
use spacing

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +export const StyledButton = styled.button<ButtonProps>`
Move this to the top of the file

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +export interface ButtonProps {
I would also set an isLoading optional prop - if you pass isLoading render a loader on the button to indicate the user that something is happening behind the scenes

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/Button.tsx
> +      {children}
{isLoading ? Loader (checkout material ui loaders) : children}

2024-11-11 11:49 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +export const StyledButton = styled.button<ButtonProps>`
Create props for the styled component - not all button props are relevant to the styled component.
Maybe you can rely on the buttonProps and leave only the relevant fields

2024-11-11 13:41 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +  children?: React.ReactNode;
done

2024-11-11 13:42 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +  variant:
done

2024-11-11 13:42 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +  size: "large" | "medium" | "small";
done

2024-11-11 15:04 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +export interface ButtonProps {
done

2024-11-11 15:04 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +  children?: React.ReactNode;
done

2024-11-11 15:04 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +    width: Hug (80px) px;
done

2024-11-11 15:04 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +    padding: 12px 16px 12px 16px;
done

2024-11-11 15:06 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +    border-radius: 4px 0px 0px 0px;
done

2024-11-11 15:06 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +    gap: 4px;
done

2024-11-11 15:06 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +export const StyledButton = styled.button<ButtonProps>`
done

2024-11-11 15:07 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/styles.ts
> +export const StyledButton = styled.button<ButtonProps>`
done

2024-11-12 06:03 UTC, kfir-azu requested changes

2024-11-12 06:03 UTC, kfir-azu commented on src/assets/components/shared/Button/styles.ts
> +export const sizeDimensions = {
Change name to buttonSizeMap (use f2 to change across all app)

2024-11-12 06:03 UTC, kfir-azu commented on src/colors.ts
> +export const spacing = {
Add values up to 40px, incrementing by 4px for each step

2024-11-12 07:26 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +export interface ButtonProps extends StyledButtonProps{
done

2024-11-12 07:26 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +  $variant,
done

2024-11-12 07:26 UTC, Ran-Regev-HLS commented on src/assets/components/shared/Button/Button.tsx
> +      {(startIcon && !isLoading) && startIcon}
done

2024-11-12 09:23 UTC, kfir-azu approved these changes

2024-11-12 14:00 UTC, merged