Feature/pokemon modal
Ran-Regev-HLS/Pokedex pull request #20
Opened 2024-11-21 08:51 UTC by Ran-Regev-HLS

### Changes Made
> added pokemon modal
> currently start a fight button starts a fight with random opponent (useage might need to be better defined)

### Checklist
> Put an x in the boxes that apply. If you're unsure about any of these, don't hesitate to ask for help.

I have:
- [ ] deleted all irrelevant comments.
- [ ] deleted all irrelevant logs and debuggers.
- [ ] deleted all sensitive information.
- [ ] made sure my code is generic and reusable for future things or reused existing resources.
- [ ] made sure that my code is readable.
- [ ] checked that the functions and resource names are self-explanatory.
- [ ] tested the code locally and it works as expected.
- [ ] added validations and error handling in relevant cases (external requests, integrations, etc).

2024-11-21 09:47 UTC, kfir-azu requested changes

2024-11-21 09:47 UTC, kfir-azu commented on src/assets/components/PokemonModal/PokemonModal.tsx
You own me a generic modal component😉

2024-11-21 09:47 UTC, kfir-azu commented on src/assets/components/PokemonModal/PokemonModal.tsx
> +                Height
use constants for all the free texts - that doesn't take time

2024-11-21 09:47 UTC, kfir-azu commented on src/assets/components/PokemonModal/PokemonModal.tsx
> +            onClick={onClick}
if it was a generic modal i would pass onclick.
if you had a generic modal component you would define in the pokemonModal component - handleStartFightClick function and pass it to the generic modal onClick prop.

bottom line - in the current implementation - if you are using the modal for specific usage create a handleStartFight function and pass it here

2024-11-21 09:47 UTC, kfir-azu commented on src/assets/components/PokemonModal/styles.ts
> +  grid-template-columns: repeat(4, 1fr);
I would check if this solution fits for different text length and supports the figma design.
i think it might break

2024-11-21 13:43 UTC, Ran-Regev-HLS commented on src/assets/components/PokemonModal/styles.ts
> +  grid-template-columns: repeat(4, 1fr);
tested with all of the pokemons and looked good

2024-12-08 07:19 UTC, kfir-azu approved these changes

2024-12-08 12:45 UTC, closed without merging