created table copmponent
Ran-Regev-HLS/Pokedex pull request #7
Opened 2024-11-17 11:36 UTC by Ran-Regev-HLS

### Changes Made
> created table component
> created layout for datatable component
> create default styling 
> allowed need functionality (sorting, filtering pagination, row click function handeling)

### Checklist
> Put an x in the boxes that apply. If you're unsure about any of these, don't hesitate to ask for help.

I have:
- [ ] deleted all irrelevant comments.
- [ ] deleted all irrelevant logs and debuggers.
- [ ] deleted all sensitive information.
- [ ] made sure my code is generic and reusable for future things or reused existing resources.
- [ ] made sure that my code is readable.
- [ ] checked that the functions and resource names are self-explanatory.
- [ ] tested the code locally and it works as expected.
- [ ] added validations and error handling in relevant cases (external requests, integrations, etc).

2024-11-17 12:27 UTC, kfir-azu requested changes
Good job!

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +  rows: { [key: string]: any }[];
That's a good place to use generics. 

```
export type TableRow<T> {
[key:string]: T
}
```

What do you think about that?

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +  searchTerm?: string;
Is the search is part of the table itself?
I think its a different component that is not related to the table

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +  const filteredRows = searchTerm
This logic should be at the parent component.
You will search in some page.
the generic dataGrid table only need to get the result of the filtered rows as the rows props and show it.

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +  const updatedColumns = columns.map((column) => ({
Why do you need this functionality?

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +        <DataGrid
Please check about:
onSortModelChange
onPaginationModelChange
rowsPerPageOptions

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +          filterModel={{
The filter shouldn't be handled inside the component

2024-11-17 12:27 UTC, kfir-azu commented on src/assets/pages/AllPokemonsPage/AllPokemonsPage.tsx
> +  { id: 1, name: "Item 1", description: "Description of Item 1" },
I Would also test what happens if you insert long text.
How does it look if you don't insert description - do you have empty state for a field in the table?
What happens if you don't send any data to the table? is it considered as an error or you show empty state?

2024-11-17 13:46 UTC, Ran-Regev-HLS commented on src/assets/components/shared/DataGridTable/DataGridTable.tsx
> +  const updatedColumns = columns.map((column) => ({
just for styling purposes (having the arrow indicating sorting without it being functional)

2024-11-17 13:56 UTC, Ran-Regev-HLS commented on src/assets/pages/AllPokemonsPage/AllPokemonsPage.tsx
> +  { id: 1, name: "Item 1", description: "Description of Item 1" },
should this handled by generic table or by indevidual col/rows definition? 
im gonna have a type called PokemonTableColumns (or something like this) and there i assumed i will handles all this (styling/empty state/overflow)

2024-11-19 10:26 UTC, kfir-azu approved these changes

2024-11-19 10:26 UTC, kfir-azu commented on src/assets/components/shared/Dropdown/Dropdown.tsx
> +  function renderItem(props: HTMLAttributes<HTMLLIElement>, option: itemType) {
```suggestion
  function renderItem(props: HTMLAttributes<HTMLLIElement>, option: OptionType) {
```

2024-11-19 10:26 UTC, kfir-azu commented on src/assets/components/shared/Dropdown/Dropdown.tsx
> +        <Box sx={itemContainerStyles}>
optionContainerStyles

2024-11-19 10:26 UTC, kfir-azu commented on src/assets/components/shared/Dropdown/Dropdown.tsx
> +      getOptionLabel={(item) => item.label}
```suggestion
      getOptionLabel={(option) => option.label}
```

2024-11-20 08:48 UTC, closed without merging